### PR TITLE
[feature] Deep Copy and Struct Mapper

### PR DESCRIPTION
**Pull request by iskra-anl**
In GitLab by @NicolasDenoyelle on Sep 14, 2020, 10:54

Tree layout feature for structures with nested pointers.

### CODE REVIEW

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Sep 14, 2020, 12:53

@perarnau check this out: Let me know if I start implementing from here.

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Sep 15, 2020, 15:17

added 1 commit

<ul><li>d818f486 - Change layout to tliling</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=10660&start_sha=747d78bed6eb12e55f0564ee31c2dddc897c2f79)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Sep 16, 2020, 09:17

added 4 commits

<ul><li>d818f486...370ccb85 - 2 commits from branch <code>staging</code></li><li>6287a46b - Draft tree layout API.</li><li>1079c611 - Change layout to tliling</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=10663&start_sha=d818f486c8cd743539c6e6c0ec7f6fc7fce9f144)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Sep 16, 2020, 10:45

added 1 commit

<ul><li>da0cffe0 - rework header to include offsets in nodes</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=10664&start_sha=1079c61137db7c54b231f3a4629bb0114b43b22f)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Sep 16, 2020, 10:51

added 1 commit

<ul><li>9d93f405 - Doc fixes</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=10665&start_sha=da0cffe0f15dcb885edc772792520fe51fce95c8)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Sep 16, 2020, 16:03

added 1 commit

<ul><li>30958159 - Add tiling tree sources</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=10669&start_sha=9d93f405f9624fb0d84e0096b309a998f24f1c76)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Sep 16, 2020, 17:01

added 1 commit

<ul><li>2ecc8cfd - Add duplication operator</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=10670&start_sha=30958159770885c0816ce3453484eae44697e366)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Sep 16, 2020, 17:05

added 1 commit

<ul><li>f0dfe3bc - Doc precision</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=10671&start_sha=2ecc8cfd7f2b2aab51c5c7955212c96ca15b0e90)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Sep 16, 2020, 17:42

added 9 commits

<ul><li>f0dfe3bc...7812272a - 2 commits from branch <code>staging</code></li><li>d0756ddc - Draft tree layout API.</li><li>2207d030 - Change layout to tliling</li><li>903e514e - rework header to include offsets in nodes</li><li>dca78a0f - Doc fixes</li><li>3a0874e3 - Add tiling tree sources</li><li>70e0a17c - Add duplication operator</li><li>26721b59 - Doc precision</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=10674&start_sha=f0dfe3bc316fd1ad37c77cc1aa83397b80383790)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Sep 18, 2020, 08:50

added 3 commits

<ul><li>932d20b3 - Take ownership on layouts.</li><li>03330258 - Add initialization test example.</li><li>c6cadd4f - wip</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=10694&start_sha=26721b59ba089db8679756e06e31713e5488f8e3)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Sep 18, 2020, 08:50

marked as a **Work In Progress** from c6cadd4fd27a37e18e363a1a9bdb62855f1f6a21

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Sep 18, 2020, 09:04

added 1 commit

<ul><li>dbd12847 - Working test dims</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=10695&start_sha=c6cadd4fd27a37e18e363a1a9bdb62855f1f6a21)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Sep 18, 2020, 16:08

added 2 commits

<ul><li>4e461ed2 - Working index operator + test</li><li>64d52467 - clang-format</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=10700&start_sha=dbd1284701f27a1cd61a7f2a0fc760a626b06abb)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Sep 18, 2020, 16:14

added 1 commit

<ul><li>a755dbd6 - Working native index operator + test</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=10701&start_sha=64d524677e34b4fc5d4a067cef08b109fd24f3e5)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Sep 18, 2020, 16:17

added 1 commit

<ul><li>200efd94 - test ntiles</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=10702&start_sha=a755dbd66d72371c18bb3292012211b012da6eff)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Sep 18, 2020, 18:14

added 1 commit

<ul><li>665a316d - test duplicate ok</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=10705&start_sha=200efd9470cc9f3239c4901f81ca63c61303ec12)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Sep 25, 2020, 09:21

added 1 commit

<ul><li>55a3b873 - clean</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=10759&start_sha=665a316d36e03c110f193d653a5df7be0b9da7ed)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Sep 25, 2020, 11:19

added 1 commit

<ul><li>e314a6c6 - move macros common out of inner-malloc</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=10760&start_sha=55a3b8739206226fe770e941f00b117203a8a4fa)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Sep 25, 2020, 14:17

added 2 commits

<ul><li>1d50c23d - Allow NULL layouts inside tiling to avoid unnecessary copies.</li><li>c286a6b9 - Allow NULL layouts inside tiling to avoid unnecessary copies.</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=10761&start_sha=e314a6c6a019e4cbd09e690a818850faf2f35fc4)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Oct 8, 2020, 14:44

added 38 commits

<ul><li>c286a6b9...43667155 - 20 commits from branch <code>staging</code></li><li>3a7ab158 - Draft tree layout API.</li><li>9adfdf9b - Change layout to tliling</li><li>d5c0dbab - rework header to include offsets in nodes</li><li>4b9e4d9b - Doc fixes</li><li>04fe7897 - Add tiling tree sources</li><li>37160ebc - Add duplication operator</li><li>e8cf6f40 - Doc precision</li><li>a42b6318 - Take ownership on layouts.</li><li>77ace9a3 - Add initialization test example.</li><li>42cb9e3a - wip</li><li>d883993d - Working test dims</li><li>6c4d4975 - Working index operator + test</li><li>ec31663a - clang-format</li><li>780cedc3 - Working native index operator + test</li><li>5ac47396 - test ntiles</li><li>cd9c618e - test duplicate ok</li><li>fdaee1ac - clean</li><li>fec117cb - move macros common out of inner-malloc</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=10877&start_sha=c286a6b9b5d97021a4a51f6ce183ed8c22ed060c)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Oct 12, 2020, 16:38

added 1 commit

<ul><li>c2d4073a - wip add hashtable and mapper abstraction with structure mapping</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=10893&start_sha=fec117cb5947cb3b6257be0773838eb30fdbddf5)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Oct 14, 2020, 17:23

added 1 commit

<ul><li>45d1bad7 - mapper abstraction that should work</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=10909&start_sha=c2d4073a2a361b137d284b036a3fd28c0f05089c)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Oct 14, 2020, 17:52

added 1 commit

<ul><li>b020878f - error fix</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=10910&start_sha=45d1bad7ae77704df4b79b67681525622385dc07)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Oct 14, 2020, 22:17

added 1 commit

<ul><li>8a241d35 - add source implementation for mapper</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=10911&start_sha=b020878fafefb5f9b2e9cdc3583d3298eae64f67)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Oct 29, 2020, 14:11

added 2 commits

<ul><li>97fd0697 - WIP</li><li>76494d5e - WIP workiing dma</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11014&start_sha=8a241d35a8f62ed477c4ba174e1f54c1775c541f)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Oct 29, 2020, 14:29

added 28 commits

<ul><li>76494d5e...2910ba2c - 2 commits from branch <code>staging</code></li><li>f7fdcbea - Draft tree layout API.</li><li>09b37ead - Change layout to tliling</li><li>0f9ee8c2 - rework header to include offsets in nodes</li><li>9023ace9 - Doc fixes</li><li>4e415df0 - Add tiling tree sources</li><li>c5e645fa - Add duplication operator</li><li>702a6423 - Doc precision</li><li>670a1cb3 - Take ownership on layouts.</li><li>bc4f2a0c - Add initialization test example.</li><li>03420860 - wip</li><li>d662ca34 - Working test dims</li><li>60d6ab7e - Working index operator + test</li><li>66c88068 - clang-format</li><li>6e3cd646 - Working native index operator + test</li><li>aa75e5a6 - test ntiles</li><li>fb6f8b2b - test duplicate ok</li><li>fda0c1bb - clean</li><li>1d265167 - move macros common out of inner-malloc</li><li>76816ded - wip add hashtable and mapper abstraction with structure mapping</li><li>1bdf0ea9 - mapper abstraction that should work</li><li>c7b888ac - error fix</li><li>615e85c0 - add source implementation for mapper</li><li>25d9e237 - WIP</li><li>71770dac - WIP workiing dma</li><li>cdae8fa7 - Fix doc</li><li>41aea388 - delete tree layout</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11016&start_sha=76494d5ed8c72a3a6c0040b8629387c435ca8ed5)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Oct 29, 2020, 14:43

added 1 commit

<ul><li>3942036f - revert useless changes</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11017&start_sha=41aea388ddcbf8e23a5a07b389b0f5bdeecdc3d4)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Oct 29, 2020, 14:51

added 1 commit

<ul><li>39b0b174 - renaming</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11018&start_sha=3942036f750942f273cd8026b4f23370ce2abbf9)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Oct 29, 2020, 14:54

added 1 commit

<ul><li>419f58b4 - Add missing test</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11019&start_sha=39b0b1749feac0c2648afabad46a9bbe4607a84d)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Oct 29, 2020, 14:55

added 1 commit

<ul><li>5712267b - remove unused function</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11020&start_sha=419f58b4994000f44e1c4a9d56e589d5323bb360)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Oct 30, 2020, 10:07

added 1 commit

<ul><li>69c09982 - Add missing file</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11023&start_sha=5712267b8aa396a2ca39e32aafd5e11c8796ca2e)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Nov 30, 2020, 19:59

added 1 commit

<ul><li>82d8730a - WIP: mapper decl macros plus bug fixes</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11260&start_sha=69c099825a05b91eb1da9858eea40c23b688c130)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Dec 3, 2020, 09:27

added 1 commit

<ul><li>1e276136 - WIP: mapper for cuda area.</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11298&start_sha=82d8730addda0f0623a27b48fedddbf1f09fe8ce)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Dec 3, 2020, 19:15

added 1 commit

<ul><li>da8cb717 - Macro with array</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11313&start_sha=1e276136567bfdfcdcbbd12745e3d5b9b88d8fe3)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Dec 3, 2020, 19:16

added 1 commit

<ul><li>b83ccf3c - WIP: fix typo</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11314&start_sha=da8cb71728dd6f4e83ef0ab71cd412c5b2a0dc58)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Dec 3, 2020, 20:36

added 2 commits

<ul><li>21546fae - working linux mapping</li><li>46120d6e - working linux mapping</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11315&start_sha=b83ccf3cdc59f78c0e509e04955f6d8fb5a04b49)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Dec 3, 2020, 22:33

added 3 commits

<ul><li>46120d6e...610cc3ef - 2 commits from branch <code>staging</code></li><li>2b3e83ad - Deep copy of structs.</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11316&start_sha=46120d6e2d17fb7c19a063c6a4becd3ca57a52bb)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Dec 4, 2020, 15:48

added 5 commits

<ul><li>6457e8ad - Remove useless layout</li><li>05f0067d - remove useless scripts</li><li>5b46a311 - doc</li><li>2828864d - Merge branch &#39;no_layout_cuda&#39; into tree_layout</li><li>df1f2aba - Better mapper</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11338&start_sha=2b3e83ad239f5c7b4f5fbb8328e1a55acb9cee97)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Dec 4, 2020, 15:52

added 1 commit

<ul><li>26a2f5e1 - install macros header</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11340&start_sha=df1f2aba540960d8ae92154af5b6aeb75f502520)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Dec 4, 2020, 15:55

added 6 commits

<ul><li>26a2f5e1...1b8d5db5 - 3 commits from branch <code>staging</code></li><li>00b27d94 - Deep copy of structs.</li><li>9f0c6580 - Better mapper</li><li>a2fb5705 - install macros header</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11341&start_sha=26a2f5e1825cabc436251a3f6b15f453df7e3769)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Dec 7, 2020, 11:41

added 1 commit

<ul><li>d3d7176f - Add __VA_OPT__ test</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11347&start_sha=a2fb570505d410bd3c673574c72c019d34778d3d)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Dec 7, 2020, 12:00

added 1 commit

<ul><li>84d7a9d5 - better print</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11348&start_sha=d3d7176f7a09f0d7b6b153b2afbef0a6d31b8367)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Dec 7, 2020, 12:02

added 1 commit

<ul><li>5538eb49 - Better mapper</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11349&start_sha=84d7a9d56d93e06a387682d973ec3737da4d9e38)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Dec 7, 2020, 15:57

added 1 commit

<ul><li>2945597c - Mapper</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11352&start_sha=5538eb49f396df1cf2bef91ed92ebdd85d7d7f58)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Dec 7, 2020, 16:03

added 1 commit

<ul><li>a78aa4c9 - test cuda unified</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11353&start_sha=2945597cf0ae7c2bc40ad2d884c1708a2296aaf0)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Dec 7, 2020, 19:14

added 1 commit

<ul><li>490d8942 - Working cuda mapper</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11356&start_sha=a78aa4c9a2c8792fcd6f0ac7cc95c98688f0e1ab)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Dec 7, 2020, 19:34

added 1 commit

<ul><li>00040267 - Faster unmap</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11357&start_sha=490d8942313a7d9a418d52583dfe642841939018)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Dec 8, 2020, 11:24

added 1 commit

<ul><li>f0ecd426 - Fix pedantic errors</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11360&start_sha=00040267e0bd2b62c63df9d2b9306c855578f366)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Dec 8, 2020, 12:26

added 1 commit

<ul><li>83f72a80 - Add tutorials for mapper</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11362&start_sha=f0ecd42609c48443a00d2a106193af8ecfb57ce4)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Dec 8, 2020, 12:50

added 1 commit

<ul><li>6858ff33 - fix memory corruption</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11364&start_sha=83f72a804a4c598bea46a0e43155a55f0a2f3510)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Dec 8, 2020, 13:03

added 1 commit

<ul><li>0ee6dbce - fix memory corruption</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11365&start_sha=6858ff337b5ec6dd8340bdc472723914bec40fe2)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Dec 8, 2020, 13:22

added 3 commits

<ul><li>5e33000e - [feature] AML deepcopy mapper</li><li>b1c9c867 - [feature] Default area for cuda unified memory.</li><li>34e3db97 - Remove not used sparse layout.</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11366&start_sha=0ee6dbceff31a82c7f998096755ddb6ee4faecd4)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Dec 8, 2020, 13:30

added 3 commits

<ul><li>019e249e - Remove unused sparse layouts.</li><li>8ad7dd20 - [feature] Default unified memory area for cuda.</li><li>c3e271d0 - [feature] AML deepcopy mapper.</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11367&start_sha=34e3db97e06c940d1b154c805d4b465607cef446)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Dec 9, 2020, 13:57

added 1 commit

<ul><li>554d7c3b - Document area constraint</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11395&start_sha=c3e271d0b9496abd7ea40813801c2cecc8e18d74)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Mar 1, 2021, 14:34

added 19 commits

<ul><li>554d7c3b...05425756 - 15 commits from branch <code>staging</code></li><li>06af0b52 - Remove unused sparse layouts.</li><li>12ab6249 - [feature] AML deepcopy mapper.</li><li>30d8f9e1 - Document area constraint</li><li>2529b049 - Add test not working</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11994&start_sha=554d7c3bce8f654790d6bccbf8327ae3a93b4fc4)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Mar 1, 2021, 15:21

added 1 commit

<ul><li>3b7aa8ee - error fix</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=11996&start_sha=2529b04988657db34613c181a4b3927b49245a56)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Mar 2, 2021, 10:51

added 1 commit

<ul><li>31581794 - Add function to deep copy the content of a structure but not the structure</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=12002&start_sha=3b7aa8ee76a3874e9fbbca248cf370eff64b5c77)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Mar 2, 2021, 11:01

added 1 commit

<ul><li>5cbbf965 - Make output size optional</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=12003&start_sha=315817946c52d1020f9ea129a5cb4d0f4217f6ca)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Mar 2, 2021, 14:34

added 1 commit

<ul><li>ea58d125 - Add mapper flags to optionnally enable copies</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=12006&start_sha=5cbbf965123742c9623200ec017b06ae4dc4985f)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Mar 11, 2021, 12:03

added 1 commit

<ul><li>9ec48173 - renaming</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=12117&start_sha=ea58d1253011b718a11dccdb700afba07107cea5)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Mar 15, 2021, 10:20

added 1 commit

<ul><li>2cf51d6f - formatting</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=12166&start_sha=f49118ed71d29cdb750d8f82eca9ca9f192fc182)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Mar 15, 2021, 10:28

added 1 commit

<ul><li>b5e84720 - peadntic fix</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=12167&start_sha=2cf51d6f4fe25cb9dd01ff9253e9a0dba61c71f3)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Mar 16, 2021, 10:13

added 18 commits

<ul><li>b5e84720...299d86d3 - 6 commits from branch <code>staging</code></li><li>54790a44 - Remove unused sparse layouts.</li><li>47837542 - [feature] AML deepcopy mapper.</li><li>9342687c - Document area constraint</li><li>01ef1649 - Add test not working</li><li>d95bc85a - error fix</li><li>39f202e2 - Add function to deep copy the content of a structure but not the structure</li><li>340d7878 - Make output size optional</li><li>83e309b4 - Add mapper flags to optionnally enable copies</li><li>58833931 - renaming</li><li>19542f8a - Doc specification and bug fix</li><li>5ea5dfce - formatting</li><li>638a0aca - peadntic fix</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=12194&start_sha=b5e84720e938e25dcec25f1acc1e08d81c88edde)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Apr 5, 2021, 12:25

added 16 commits

<ul><li>638a0aca...b0e5f921 - 4 commits from branch <code>staging</code></li><li>e12e1df1 - Remove unused sparse layouts.</li><li>bd168d30 - [feature] AML deepcopy mapper.</li><li>6f79dcc7 - Document area constraint</li><li>4fa7e82e - Add test not working</li><li>d2227a7c - error fix</li><li>43329e5c - Add function to deep copy the content of a structure but not the structure</li><li>d51d0543 - Make output size optional</li><li>2f0af204 - Add mapper flags to optionnally enable copies</li><li>7c6d9c49 - renaming</li><li>ef252343 - Doc specification and bug fix</li><li>0752f72c - formatting</li><li>cc08099d - peadntic fix</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=12458&start_sha=638a0acae5cbbc7bc533f9f4cea28b08eee607da)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Apr 9, 2021, 18:10

added 21 commits

<ul><li>cc08099d...715a4251 - 4 commits from branch <code>staging</code></li><li>26ec2cca - Default dma instanciation</li><li>ccf46774 - Compiling tests</li><li>378cdcff - Working tests</li><li>f39869ed - rebase fixes</li><li>a7520b62 - Remove unused sparse layouts.</li><li>70fa5811 - [feature] AML deepcopy mapper.</li><li>aa1ed906 - Document area constraint</li><li>2736d425 - Add test not working</li><li>b039747d - error fix</li><li>763c8da1 - Add function to deep copy the content of a structure but not the structure</li><li>c4c2f84f - Make output size optional</li><li>88169ed7 - Add mapper flags to optionnally enable copies</li><li>e7e71ae2 - renaming</li><li>db5ac46b - Doc specification and bug fix</li><li>a2580fbb - formatting</li><li>77ce2df3 - peadntic fix</li><li>c7a06259 - wip</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=12514&start_sha=cc08099d265121c49afa3d8ba818516be48cc7c6)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Apr 13, 2021, 14:50

added 1 commit

<ul><li>28eddbe8 - working mapper with split allocations</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=12518&start_sha=c7a0625921ff462f4adbeec21b48ec65b1d17192)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Apr 13, 2021, 14:54

added 1 commit

<ul><li>772db2a4 - fix feature special code</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=12519&start_sha=28eddbe8d4ca6425c61767e7254bc1426c30d515)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Apr 14, 2021, 11:31

added 2 commits

<ul><li>b2d8508c - Doc + interface</li><li>b270a8fa - doc typo</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=12530&start_sha=772db2a46ab7041d626dc697c291f6874cacb47a)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Apr 14, 2021, 11:43

added 1 commit

<ul><li>15a508b3 - Doc + interface</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=12531&start_sha=b270a8fa53b042141eec27c7378ad1d768ca5015)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Apr 14, 2021, 12:00

added 1 commit

<ul><li>36aeec79 - header guard</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=12532&start_sha=15a508b310b610d03bb8c3c47ee2b6eee841995c)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Apr 14, 2021, 13:15

added 1 commit

<ul><li>86840402 - fix shallow mapper</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=12533&start_sha=36aeec79aa4c878643e0632c2900d84610c5eb03)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Apr 14, 2021, 15:24

added 1 commit

<ul><li>735ea8e5 - fix shallow mapper</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=12534&start_sha=8684040204ab63dd329b4e6a9210c8ba2771a7b3)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Apr 14, 2021, 15:59

added 2 commits

<ul><li>59d33682 - bug fix</li><li>e16404ee - Check NULL user pointer. Use it as a guard and do not descend mapper with NULL pointer.</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=12535&start_sha=735ea8e54db91555568ff0ada088b383e7fbfd48)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Apr 16, 2021, 13:11

added 1 commit

<ul><li>1cdb5fcc - Fix munmap leak and make single copy per field in mapper</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=12557&start_sha=e16404ee62805992010b7d74b283b35a869abbfb)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Apr 16, 2021, 13:36

added 1 commit

<ul><li>bdf8c235 - fix unmap recursive</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=12558&start_sha=1cdb5fcc8104d6ff6336ddc67c1faa85aa446608)

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Apr 16, 2021, 13:47

added 1 commit

<ul><li>9e68f687 - fix munmap</li></ul>

[Compare with previous version](/argo/aml/-/merge_requests/156/diffs?diff_id=12559&start_sha=bdf8c2350452326d2abb88539da944a33cad4d58)

**Review by perarnau — CHANGES_REQUESTED** [review]
- [x] exchange src and dst for mapper_copy

**Review by perarnau — APPROVED** [review]

**Pull request merged**
